all files that are tracked
ellikap6/CodeU-team11 pull request #18
Opened 2019-04-12 04:54 UTC by ChuyueSun

2019-04-12 04:59 UTC, ChuyueSun commented
<img width="921" alt="Screen Shot 2019-04-12 at 12 57 51 AM" src="https://user-images.githubusercontent.com/33578456/56013323-2d982c80-5cbe-11e9-9b88-58312c8994be.png">
<img width="815" alt="Screen Shot 2019-04-12 at 12 58 22 AM" src="https://user-images.githubusercontent.com/33578456/56013327-2ffa8680-5cbe-11e9-8e6e-ba100fc730da.png">

2019-04-12 21:33 UTC, tsalako requested changes
Can you add a screenshot of the chart?

2019-04-12 21:33 UTC, tsalako commented on src/main/webapp/chart.html
> +                // var newDate = new Date(timestampAsDate.getYear(), timestampAsDate.getMonth(), timestampAsDate.getDay());
we dont need this comment.

2019-04-16 19:18 UTC, ChuyueSun reviewed
<img width="847" alt="Screen Shot 2019-04-16 at 3 17 52 PM" src="https://user-images.githubusercontent.com/33578456/56237806-e5c92a80-605a-11e9-9eac-4f8f7f6063bd.png">
This is what it currently looks like...

2019-04-16 19:18 UTC, ChuyueSun commented on src/main/webapp/chart.html
> +                // var newDate = new Date(timestampAsDate.getYear(), timestampAsDate.getMonth(), timestampAsDate.getDay());
What do you mean?

2019-04-16 22:46 UTC, tsalako commented
The chart doesnt seem to be working. Can you look into fixing it/see where it is breaking down.

2019-04-16 22:47 UTC, tsalako commented on src/main/webapp/chart.html
> +                // var newDate = new Date(timestampAsDate.getYear(), timestampAsDate.getMonth(), timestampAsDate.getDay());
newDate isnt commented out and we dont need it so you can remove the comment.

2019-04-18 01:25 UTC, closed without merging